
services:
  db_user:
    container_name: autogreen_userdb
    image: postgres:17
    volumes:
      - userdb:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: autogreen1234
      POSTGRES_DB: userdb
    ports:
      - "5432:5432"
  db_sensor: 
    container_name: autogreen_sensordb
    image: postgres:17
    volumes:
      - sensordb:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: autogreen1234
      POSTGRES_DB: sensordb
    ports:
      - "5431:5432"
  db_timescale:
    container_name: autogreen_timescaledb
    image: timescale/timescaledb-ha:pg17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: autogreen1234
      POSTGRES_DB: timescaledb
    ports:
      - "5433:5432"
    # docker exec -it timescaledb psql -d "postgres://postgres:password@localhost/postgres"
    # to connect to postgres use above command

volumes:
  userdb: {}
  sensordb: {}
  timescaledb: {}
