apiVersion: apps/v1
kind: Deployment
metadata:
  name: autogreen-deployment
  labels:
    app: autogreen
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autogreen
  template:
    metadata:
      labels:
        app: autogreen
    spec:
      containers:
      - name: sensordb
        image: postgres:17
        ports:
        - containerPort: 80
        resources:
          requests: 
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
      - name: userdb
        image: postgres:17
        ports:
        - containerPort: 81
        resources:
          requests: 
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
      - name: timescaledb
        image: timescale/timescaledb-ha:pg17
        ports:
        - containerPort: 82
        resources:
          requests: 
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
      - name: autogreen-frontend
        image: zoravoid/autogreen:01
        ports:
        - containerPort: 83
        resources:
          requests: 
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"

#apply deployment
#kubectl apply -fautogreen-deployment.yaml
#check if pods are created
#kubectl get pods -A