apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
  labels:
    app: user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
      - name: userdb
        image: postgres:17
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: userdb-secret
              key: userdb-user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: userdb-secret
              key: userdb-password
---
apiVersion: v1
kind: Service
metadata:
  name: userdb-service
spec:
  selector:
    app: sensor
  ports:
  - protocol: TCP
    port: 3002
    targetPort: 5432
