FROM python:3.12-slim

WORKDIR /usr/src/app

RUN python3 -m venv /opt/venv

COPY . .

RUN . /opt/venv/bin/activate && pip install -r requirements.txt

CMD . /opt/venv/bin/activate && exec python3 app.py